


from tale.base import Item


class Book(Item):
    """ A book that can be read. If text is not supplied, it will be 
    generated by the llm."""

    def __init__(self, name, description, pageSize: int = 1, pages: list = [] ):
        super(Book, self).__init__(name, description)
        self.text = ''

    def read(self):
        if not self.text:
            pass
        return self.text
